REVOKE ALL ON FUNCTION public.consume_rate_limit(text, integer, numeric, integer) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.purge_security_events(interval) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.run_security_events_purge(interval) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.update_updated_at() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.is_admin(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.is_chw(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.find_nearest_chw(numeric, numeric, integer) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.calculate_distance_km(numeric, numeric, numeric, numeric) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.security_events_retention_status() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.security_events_summary(timestamptz) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.security_top_ips(timestamptz, integer) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.admin_run_security_events_purge(interval) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.log_admin_action(text, text, uuid, text, jsonb) FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.consume_rate_limit(text, integer, numeric, integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.purge_security_events(interval) TO service_role;
GRANT EXECUTE ON FUNCTION public.run_security_events_purge(interval) TO service_role;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO service_role;
GRANT EXECUTE ON FUNCTION public.update_updated_at() TO service_role;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.is_admin(uuid) TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.is_chw(uuid) TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.find_nearest_chw(numeric, numeric, integer) TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_distance_km(numeric, numeric, numeric, numeric) TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.security_events_retention_status() TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.security_events_summary(timestamptz) TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.security_top_ips(timestamptz, integer) TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.admin_run_security_events_purge(interval) TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.log_admin_action(text, text, uuid, text, jsonb) TO service_role, authenticated;